server:
  port: 8989
  context-path: /ssm
  jsp-servlet:
    init-parameters:
        development: true  #开启jsp页面的调试模式

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSourceC3P0Adapter
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uesr?useUnicode=true&amp;characterEncoding=utf8&amp;serverTimezone=GMT
    username: root
    password: root
mybatis:
  mapper-locations: classpath:com.zbw.mapper/*.xml
  type-aliases-package: com.zbw.model